### ISSUE TITLE
Provide instructions on how to generate the mapability file (or where to download)

### ISSUE THREAD

**Issue by amcpherson** [adoebley/Griffin#1]
Help on where to obtain the mapability file or how to generate would be greatly appreciated!

**Comment by amcpherson** [comment]
I assume single-read k50 umap from here:https://bismap.hoffmanlab.org/ would work?

**Comment by adoebley** [comment]
Hi @amcpherson! You can download that file from:
https://hgdownload.soe.ucsc.edu/gbdb/hg38/hoffmanMappability/k50.Umap.MultiTrackMappability.bw

**Comment by adoebley** [comment]
link provided
