### ISSUE TITLE
Running Griffin on TSS

### ISSUE THREAD

**Issue by Irfanwustl** [adoebley/Griffin#12]
Hi,
Thanks for the great tool. While I was able to run Griffin on TFBS using your demo, I am wondering how we can run it in TSS. In the TFBS case, for every TF Griffin needs a dedicated file of many binding sites for that particular TF. However, for TSS, every gene has **only one** TSS. So, how should we provide the TSS info?  A demo will be very helpful.

Thanks

**Comment by adoebley** [comment]
Hi, 

Thanks for the question!

You can provide the TSS info in a single TSV file and then make a few changes to the config to analyze sites individually:

chrom_column: <name of chrom column>
position_column: <position of TSS>
strand_column: <name of strand column> 
chroms: <include chrX and chrY>

CNA_normalization: True #normalizes the coverage around each TSS to 1 so you can compare samples with different copy numbers for a given TSS (norm_window is +/- 5000 bp by default)
individual: True #save the coverage at each TSS separately
exclude_outliers: False #when looking at individual sites, you don't need to exclude outlier positions within sites

I added an example config in the development branch:
[https://github.com/adoebley/Griffin/blob/development/snakemakes/griffin_nucleosome_profiling/config/config_TSS.yaml](https://github.com/adoebley/Griffin/blob/development/snakemakes/griffin_nucleosome_profiling/config/config_TSS.yaml)

To make sure your reverse TSS are getting flipped properly, look for a line like this in the log and check that there are 0 undirected sites:
Total sites (fw/rv/undirected/total): 18112/17805/0/35917

Let me know if you have any more questions or this isn't working for you!

-Anna-Lisa

**Comment by Irfanwustl** [comment]
Many thanks. However, it seems the example config file link you provided does not exist. Can you please have a look?

-Irfan

**Comment by adoebley** [comment]
Hi Irfan, 

Sorry about that. I fixed the link above. Let me know if it's still not working.

-Anna-Lisa

**Comment by Irfanwustl** [comment]
Hi,
Thank you so much for the fix. It is almost working but I am facing two issues now.


1. For some TSS, I am getting errors in rule merge_sites. I have attached such a region 
[SYN3.txt](https://github.com/adoebley/Griffin/files/11770766/SYN3.txt). Using the demo file from [here](https://github.com/adoebley/Griffin/tree/main/demo/bam), we can reproduce the error. 

2. If I supply the TSS where I am not getting the error mentioned above, I am facing another issue. It seems in the generated tsv result file, the site name is all same and it is the site name provided by the sites.yaml file. (as I am providing one file for all TSS, I just mentioned one site name in the yaml file) I have attached such a result  for 10 TSS. It has 10 rows but the site name is all same. Here is the result file:  [Healthy_demo.GC_corrected.coverage.txt](https://github.com/adoebley/Griffin/files/11770861/Healthy_demo.GC_corrected.coverage.txt).
And the corresponding sites.yaml: 
[sites.txt](https://github.com/adoebley/Griffin/files/11770882/sites.txt). 

I think I am missing some thing. Will you please have a look?

Best,
Irfan
