### ISSUE TITLE
How to make site_lists

### ISSUE THREAD

**Issue by RetGiraffe11235** [adoebley/Griffin#16]
Hi Developer,

Thank you for creating such a useful tool for tumor classification. 
I'm sorry for a lack of understanding of this tool, but how do we indicate the site file on the nucleosome_profiling step? I understood the current version of Griffin doesn't require site filtration prior to analysis. However, it still requires the site file. If I run Griffin using our data, can we divert the demo site file for running?
Thank you for your great effort in maintaining this tool.

Best,
Tomoki

**Comment by liujilei2233** [comment]
+1

Looking forward to a response from the author team！

**Comment by adoebley** [comment]
Thanks for the question and sorry for the huge delay in responding! You can specify the sites file by modifying `config/sites.yaml` to include the name of your sites file and the path to that file. This is step 7 under "nucleosome profiling" in the Wiki:

7. Open the sites.yaml (run_demo/griffin_nucleosome_profiling/config/sites.yaml) and update the path to the demo sites file:  
	> site_lists:  
	>   CTCF_demo: ../../demo/griffin_nucleosome_profiling_demo_files/sites/CTCF.hg38.1000.txt 
	

For instance if you have two sites files "sites1.txt" and "sites2.txt" you would modify the config to contain: 

> site_lists:  
>   sites1: path/to/sites1.txt 
>   sites2: path/to/sites2.txt 

Hope that helps! I'm going to close this issue for now but feel free to re-open it if you have follow up questions.
