### ISSUE TITLE
Running Griffin using different read depths

### ISSUE THREAD

**Issue by Januaryyiyue** [adoebley/Griffin#18]
Hi,

I was wondering if Griffin results would be different if 1) the initial read depth is different (e.g., 30x vs. 1x) or 3) the downsampling is different (e.g., downsampled to 1x vs. not downsampled).

Thank you so much!

**Comment by adoebley** [comment]
Thanks for the question! The coverage profiles should stay the same on average but will get noisier as the read depth gets lower. If the read depth is too low, the noise will obscure the signal. The exact depth at which this happens depends on the strength of the signal.

Feel free to reopen the issue if you have follow up questions!
