### ISSUE TITLE
Error with Griffin Nucleosome Profiling 

### ISSUE THREAD

**Issue by sashamain** [adoebley/Griffin#7]
Hi @adoebley ,
Thank you for creating this pipeline - it's fantastic. However, I have been having an issue when trying to run the nucleosome positioning portion for a second time. For context, I ran the pipeline and wanted to look at two different site reference files but accidentally named them the same, so the second overwrote the first. When trying to rerun the pipeline using the same site files, I got the following error.

```{bash}

Traceback (most recent call last):
  File "../../scripts/griffin_coverage.py", line 316, in <module>
    all_sites_bed = all_sites_bed.sort()
  File "/cluster/home/smain/software/conda/miniconda3/envs/griffin_env/lib/python3.7/site-packages/pybedtools/bedtool.py", line 840, in decorated
    result = method(self, *args, **kwargs)
  File "/cluster/home/smain/software/conda/miniconda3/envs/griffin_env/lib/python3.7/site-packages/pybedtools/bedtool.py", line 345, in wrapped
    decode_output=decode_output,
  File "/cluster/home/smain/software/conda/miniconda3/envs/griffin_env/lib/python3.7/site-packages/pybedtools/helpers.py", line 434, in call_bedtools
    raise BEDToolsError(subprocess.list2cmdline(cmds), stderr)
pybedtools.helpers.BEDToolsError:
Command was:

        bedtools sort -i /cluster/projects/scottgroup/people/sasha/Griffin/griffin_chromvar_fig/griffin_nucleosome_profiling/tmp/CAMA1_00/tmp_pybedtools/pybedtools.3hlvz7od.tmp

Error message was:
Unexpected file format.  Please use tab-delimited BED, GFF, or VCF. Perhaps you have non-integer starts or ends at line 1?
  
```

I eventually gave up troubleshooting (I am a snakemake novice). I recloned your GitHub and remade the conda environment to start from scratch. Again the pipeline ran seamlessly, but when I tried to do a second analysis (with different site files this time), it failed for the nucleosome positioning part with the same error. 

Please let me know if you have any suggestions for this, and thanks!

UPDATE: This was an issue with the sites files. I was converting my bedfiles to txt format and adding the header as required - something must have gone wrong. I remade them and it works now.

**Comment by adoebley** [comment]
Thanks for reaching out and glad you figured out the problem! Let me know if you have any trouble in the future!
